# Generated by Django 5.2.5 on 2026-03-03 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdleReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant', models.CharField(choices=[('plant_1', 'Plant 1'), ('plant_2', 'Plant 2')], default='plant_2', max_length=20)),
                ('machine_no', models.CharField(max_length=10)),
                ('operator_name', models.CharField(max_length=100)),
                ('tool_id', models.CharField(max_length=100)),
                ('reason', models.CharField(choices=[('TOOL_BD', 'Tool Breakdown'), ('MC_BD', 'Machine Breakdown'), ('MAINT', 'Scheduled Maintenance'), ('CHANGEOVER', 'Changeover'), ('NO_MATERIAL', 'Material Shortage'), ('QUALITY_ISSUE', 'Quality Issue'), ('OTHER', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'idle_reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_account', models.CharField(max_length=255)),
                ('part_name', models.CharField(max_length=255)),
                ('operation', models.CharField(max_length=255)),
                ('part_number', models.CharField(blank=True, max_length=255, null=True)),
                ('plant_location', models.CharField(max_length=100)),
                ('inspection_date', models.DateField()),
                ('operator_name', models.CharField(max_length=100)),
                ('machine_number', models.CharField(max_length=50)),
                ('inspection_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inspection_reports',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='L1_PartInfoMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('part_no', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'L1_part_info_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='L2_ProcessReportMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'L2_process_report_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='L3_ParameterDetailMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PRODUCT', 'PRODUCT'), ('PROCESS', 'PROCESS')], max_length=50)),
                ('parameter_name', models.CharField(max_length=200)),
                ('specification', models.CharField(max_length=200)),
                ('instrument', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'L3_parameter_detail_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plant', models.CharField(choices=[('plant_1', 'Plant 1'), ('plant_2', 'Plant 2')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'operators',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperatorAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant', models.CharField(choices=[('plant_1', 'Plant 1'), ('plant_2', 'Plant 2')], default='plant_2', max_length=20)),
                ('machine_no', models.CharField(max_length=10)),
                ('operator_name', models.CharField(max_length=100)),
                ('shift', models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B')], max_length=1)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'operator_assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plant2HourlyIdletime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('tool_id', models.CharField(max_length=50)),
                ('machine_no', models.CharField(max_length=10)),
                ('idle_time', models.IntegerField(default=0)),
                ('shut_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shift', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Plant2_hourly_idle',
                'ordering': ['-timestamp', 'machine_no'],
                'indexes': [models.Index(fields=['timestamp', 'machine_no'], name='Plant2_hour_timesta_1dc870_idx'), models.Index(fields=['machine_no', 'timestamp'], name='Plant2_hour_machine_7eaa1f_idx')],
                'unique_together': {('timestamp', 'machine_no')},
            },
        ),
    ]
