# Generated by Django 5.2.5 on 2025-09-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdleReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_no', models.CharField(max_length=10)),
                ('operator_name', models.CharField(max_length=100)),
                ('tool_id', models.CharField(max_length=100)),
                ('reason', models.CharField(choices=[('TOOL_BD', 'Tool Breakdown'), ('MC_BD', 'Machine Breakdown'), ('MAINT', 'Scheduled Maintenance'), ('CHANGEOVER', 'Changeover'), ('NO_MATERIAL', 'Material Shortage'), ('QUALITY_ISSUE', 'Quality Issue'), ('OTHER', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'idle_reports',
            },
        ),
        migrations.CreateModel(
            name='OperatorAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_no', models.CharField(max_length=10)),
                ('operator_name', models.CharField(max_length=100)),
                ('shift', models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B')], max_length=1)),
                ('start_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'operator_assignments',
            },
        ),
    ]
