# Generated by Django 5.2.5 on 2025-11-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idlereport',
            name='plant',
            field=models.CharField(choices=[('plant_1', 'Plant 1'), ('plant_2', 'Plant 2')], default='plant_2', max_length=20),
        ),
        migrations.AddField(
            model_name='operatorassignment',
            name='plant',
            field=models.CharField(choices=[('plant_1', 'Plant 1'), ('plant_2', 'Plant 2')], default='plant_2', max_length=20),
        ),
        migrations.AlterField(
            model_name='operatorassignment',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plant', models.CharField(choices=[('plant_1', 'Plant 1'), ('plant_2', 'Plant 2')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'operators',
                'ordering': ['name'],
                'unique_together': {('name', 'plant')},
            },
        ),
    ]
