# Generated by Django 5.2.5 on 2026-03-23 11:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineChecksheetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('shift', models.CharField(max_length=10)),
                ('machine_no', models.CharField(max_length=50)),
                ('operator_name', models.CharField(max_length=100)),
                ('supervisor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'machine_checksheet_report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IncomingInspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('supplier_name', models.CharField(max_length=255)),
                ('grn_no', models.CharField(max_length=100)),
                ('qty_received', models.PositiveIntegerField()),
                ('qty_inspected', models.PositiveIntegerField()),
                ('qty_accepted', models.PositiveIntegerField()),
                ('qty_rejected', models.PositiveIntegerField(default=0)),
                ('inspected_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.l1_partinfomaster')),
            ],
            options={
                'db_table': 'incoming_inspection_report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IncomingInspectionObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255)),
                ('specification', models.CharField(max_length=255)),
                ('obs_1', models.CharField(blank=True, max_length=100, null=True)),
                ('obs_2', models.CharField(blank=True, max_length=100, null=True)),
                ('obs_3', models.CharField(blank=True, max_length=100, null=True)),
                ('obs_4', models.CharField(blank=True, max_length=100, null=True)),
                ('obs_5', models.CharField(blank=True, max_length=100, null=True)),
                ('inspection_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='api.incominginspectionreport')),
            ],
            options={
                'db_table': 'incoming_inspection_observation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MachineChecksheetObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(max_length=10)),
                ('check_point', models.CharField(max_length=255)),
                ('specification', models.CharField(max_length=255)),
                ('checking_method', models.CharField(max_length=255)),
                ('observed_value', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('is_ok', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_points', to='api.machinechecksheetreport')),
            ],
            options={
                'db_table': 'machine_checksheet_observation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DailyProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('shift', models.CharField(max_length=5)),
                ('plant', models.CharField(max_length=20)),
                ('machine_no', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('working_time_min', models.IntegerField(default=0)),
                ('total_production', models.IntegerField(default=0)),
                ('target_production', models.IntegerField(default=0)),
                ('ok_quantity', models.IntegerField(default=0)),
                ('rejection_qty', models.IntegerField(default=0)),
                ('rework_qty', models.IntegerField(default=0)),
                ('not_confirm_qty', models.IntegerField(default=0, verbose_name='Not Confirm / Hold Qty')),
                ('tool_setup_min', models.IntegerField(default=0)),
                ('machine_bd_min', models.IntegerField(default=0, verbose_name='Machine Breakdown Min')),
                ('tool_bd_min', models.IntegerField(default=0, verbose_name='Tool Breakdown Min')),
                ('coil_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='production_reports', to='api.l2_processreportmaster')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_reports', to='api.operator')),
                ('part_info', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='production_reports', to='api.l1_partinfomaster')),
            ],
            options={
                'db_table': 'daily_production_report',
                'managed': True,
                'unique_together': {('report_date', 'shift', 'machine_no', 'part_info')},
            },
        ),
    ]
