# Generated by Django 5.2.5 on 2026-06-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bintrolleyreport',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dailyproductionreport',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fourmchangeinspection',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fourmdisplay',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tipchangedressing',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
