# Generated by Django 5.2.5 on 2026-06-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bintrolleyreport_prepared_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodreceiptentry',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='redbinanalysisreport',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='redbinattendance',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='scrapnoteentry',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
