# Generated by Django 5.2.5 on 2025-12-20 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_idlereport_plant_operatorassignment_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorassignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='operatorassignment',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
