# Generated by Django 5.2.5 on 2026-03-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_machinechecksheetreport_incominginspectionreport_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinechecksheetobservation',
            options={'managed': True, 'ordering': ['s_no']},
        ),
        migrations.RenameField(
            model_name='machinechecksheetobservation',
            old_name='check_point',
            new_name='poka_yoke_detail',
        ),
        migrations.RenameField(
            model_name='machinechecksheetreport',
            old_name='supervisor_name',
            new_name='checked_by_maintenance',
        ),
        migrations.RemoveField(
            model_name='machinechecksheetobservation',
            name='observed_value',
        ),
        migrations.RemoveField(
            model_name='machinechecksheetobservation',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='machinechecksheetobservation',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='machinechecksheetreport',
            name='operator_name',
        ),
        migrations.RemoveField(
            model_name='machinechecksheetreport',
            name='shift',
        ),
        migrations.AddField(
            model_name='machinechecksheetobservation',
            name='reference_sop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machinechecksheetreport',
            name='plant_name',
            field=models.CharField(default='Plant 1', max_length=100),
        ),
        migrations.AddField(
            model_name='machinechecksheetreport',
            name='verified_by_production',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machinechecksheetobservation',
            name='s_no',
            field=models.PositiveIntegerField(),
        ),
    ]
