# Generated by Django 5.2.5 on 2026-04-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_machinechecksheetobservation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipChangeDressing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('prd_qty', models.IntegerField()),
                ('tip_change', models.CharField(max_length=10)),
                ('tip_dressing', models.CharField(max_length=10)),
                ('dressing_status', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tip_change_dressing',
                'managed': True,
            },
        ),
    ]
