# Generated by Django 5.2.5 on 2026-04-09 07:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_machinechecksheetobservation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiveSChecksheetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='P.Shop & Parking area', max_length=100)),
                ('zone_leader', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('language', models.CharField(max_length=10)),
                ('total_checks', models.IntegerField(default=0)),
                ('ok_count', models.IntegerField(default=0)),
                ('ng_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'five_s_checksheet_report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FiveSChecksheetObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_category', models.CharField(max_length=10)),
                ('check_point', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='api.fiveschecksheetreport')),
            ],
            options={
                'db_table': 'five_s_observation',
                'managed': True,
            },
        ),
    ]
