# Generated by Django 5.2.5 on 2025-12-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_operatorassignment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant2HourlyIdle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('machine_no', models.CharField(db_index=True, max_length=10)),
                ('tool_id', models.CharField(blank=True, max_length=50, null=True)),
                ('idle_minutes', models.IntegerField(default=0)),
                ('shut_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shift', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Plant2_hourly_idle',
                'ordering': ['-timestamp', 'machine_no'],
                'indexes': [models.Index(fields=['timestamp', 'machine_no'], name='Plant2_hour_timesta_1dc870_idx'), models.Index(fields=['machine_no', 'timestamp'], name='Plant2_hour_machine_7eaa1f_idx')],
            },
        ),
    ]
