# Generated by Django 5.2.5 on 2026-06-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_goodreceiptentry_prepared_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductionplan',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
