# Generated by Django 5.2.5 on 2025-12-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_plant2hourlyidle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant2HourlyIdletime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('tool_id', models.CharField(max_length=50)),
                ('machine_no', models.CharField(max_length=10)),
                ('idle_time', models.IntegerField(default=0)),
                ('shut_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shift', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'Plant2_hourly_idle',
                'ordering': ['-timestamp', 'machine_no'],
            },
        ),
        # migrations.DeleteModel(
        #     name='Plant2HourlyIdle',
        # ),
        migrations.AddIndex(
            model_name='plant2hourlyidletime',
            index=models.Index(fields=['timestamp', 'machine_no'], name='Plant2_hour_timesta_1dc870_idx'),
        ),
        migrations.AddIndex(
            model_name='plant2hourlyidletime',
            index=models.Index(fields=['machine_no', 'timestamp'], name='Plant2_hour_machine_7eaa1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plant2hourlyidletime',
            unique_together={('timestamp', 'machine_no')},
        ),
    ]
