# Generated by Django 5.2.5 on 2026-04-10 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fiveschecksheetreport_fiveschecksheetobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinTrolleyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('week', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=20)),
                ('checkpoints', models.JSONField(blank=True, default=dict, null=True)),
                ('cleaning_details', models.JSONField(blank=True, default=dict, null=True)),
                ('maintenance_details', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bin_trolley_report',
                'ordering': ['-date', '-created_at'],
                'managed': True,
            },
        ),
    ]
