# Generated by Django 5.2.5 on 2026-06-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_machinebreakdownintimation_prepared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cncmaintenancereport',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
