# Generated by Django 5.2.5 on 2026-04-11 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bintrolleyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('special_char', models.CharField(blank=True, max_length=100, null=True)),
                ('spec', models.CharField(blank=True, max_length=100, null=True)),
                ('tolerance', models.CharField(blank=True, max_length=50, null=True)),
                ('inst', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'inspection_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RedBinAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('part_name_model', models.CharField(max_length=255)),
                ('operation', models.CharField(max_length=255)),
                ('total_rej_qty', models.PositiveIntegerField()),
                ('defect_detail', models.TextField()),
                ('root_cause_reason', models.TextField()),
                ('action_taken', models.TextField()),
                ('responsible_person', models.CharField(max_length=150)),
                ('target_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'red_bin_analysis_report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScrapNoteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('part_name', models.CharField(max_length=255)),
                ('part_no', models.CharField(max_length=100)),
                ('defect_detail', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scrap_note_entry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RedBinAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('employee_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('', 'Unmarked')], default='', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'red_bin_attendance',
                'managed': True,
                'unique_together': {('date', 'employee_name')},
            },
        ),
    ]
