# Generated by Django 5.2.5 on 2026-04-13 03:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_inspectionitem_redbinanalysisreport_scrapnoteentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReworkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('remark', models.TextField(blank=True, null=True)),
                ('part_name', models.CharField(max_length=255)),
                ('part_no', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=255)),
                ('non_conformance', models.CharField(max_length=255)),
                ('rework_qty', models.PositiveIntegerField(default=0)),
                ('inspected_by', models.CharField(blank=True, max_length=150, null=True)),
                ('dynamic_details', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rework_entry',
                'ordering': ['-date', '-created_at'],
                'managed': True,
            },
        ),
    ]
