# Generated by Django 5.2.5 on 2026-04-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pushsubscription'),
        ('api', '0007_reworkentry'),
    ]

    operations = [
    ]
