# Generated by Django 5.2.5 on 2026-06-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_machinepreventivemaintenance_prepared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerpresspmchecksheet',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
