# Generated by Django 5.2.5 on 2026-04-13 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_0005_pushsubscription_0007_reworkentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name_no', models.CharField(max_length=255, verbose_name='Tool Name/No.')),
                ('location', models.CharField(max_length=255)),
                ('problem', models.TextField()),
                ('reason_for_deviation', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.CharField(max_length=100)),
                ('prod_incharge', models.CharField(blank=True, max_length=150, null=True)),
                ('qa_incharge', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deviation_approval',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
