# Generated by Django 5.2.5 on 2026-04-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_deviationapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPowerPressChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=50)),
                ('operator_name', models.CharField(max_length=100)),
                ('machine_no', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('checkpoints', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
