# Generated by Django 5.2.5 on 2026-04-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dailypowerpresschecksheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineBreakdownIntimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_date', models.DateField(blank=True, null=True)),
                ('given_time', models.TimeField(blank=True, null=True)),
                ('machine_name_no', models.CharField(max_length=255)),
                ('breakdown_name', models.CharField(max_length=255)),
                ('part_made_after_inspection', models.CharField(max_length=255)),
                ('breakdown_desc', models.TextField()),
                ('repair_date', models.DateField(blank=True, null=True)),
                ('repair_time', models.TimeField(blank=True, null=True)),
                ('repair_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mechanics_count', models.IntegerField(blank=True, null=True)),
                ('repair_desc', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='OK', max_length=10)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('verification_time', models.TimeField(blank=True, null=True)),
                ('language', models.CharField(default='english', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'machine_breakdown_intimation',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MachineHistoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=255)),
                ('machine_no', models.CharField(max_length=100)),
                ('machine_specs', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('history_records', models.JSONField(default=list)),
                ('prepared_by', models.CharField(blank=True, max_length=150, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'machine_history_card',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
