# Generated by Django 5.2.5 on 2026-04-14 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_machinebreakdownintimation_machinehistorycard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolHistoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_date', models.DateField(blank=True, null=True)),
                ('part_name', models.CharField(max_length=255)),
                ('part_no', models.CharField(max_length=100)),
                ('tool_name', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_tool_life', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_maintenance_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('prod', models.CharField(blank=True, max_length=100, null=True)),
                ('resharpening_stroke', models.CharField(blank=True, max_length=100, null=True)),
                ('cumulative_prod', models.CharField(blank=True, max_length=100, null=True)),
                ('problem_reported', models.TextField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('updated_in_4m', models.CharField(blank=True, max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tool_history_report',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ToolPreventiveMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('tool_name', models.CharField(max_length=255)),
                ('part_name', models.CharField(blank=True, max_length=255, null=True)),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('operation_no', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_person', models.CharField(max_length=150)),
                ('maintenance_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tool_prev_maintenance',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
