# Generated by Django 5.2.5 on 2026-04-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_toolhistoryreport_toolpreventivemaintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodReceiptEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('specification', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.CharField(choices=[('QA', 'QA'), ('IT', 'IT'), ('IOT', 'IOT'), ('PRODUCTION', 'PRODUCTION'), ('HR', 'HR'), ('MAINTENANCE', 'MAINTENANCE'), ('PURCHASE', 'PURCHASE')], max_length=50)),
                ('qty', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('received_by', models.CharField(max_length=255)),
                ('received_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
