# Generated by Django 5.2.5 on 2026-06-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_dailypowerpresschecksheet_prepared_by'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bintrolleyreport',
            table='"production"."bin_trolley_report"',
        ),
    ]
