# Generated by Django 5.2.5 on 2026-04-15 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_goodreceiptentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_no', models.CharField(blank=True, max_length=50, null=True)),
                ('operator_name', models.CharField(max_length=150)),
                ('part_name', models.CharField(max_length=150)),
                ('part_no', models.CharField(max_length=100)),
                ('operation_name', models.CharField(max_length=150)),
                ('planned_quantity', models.PositiveIntegerField()),
                ('qty_remark', models.TextField(blank=True, null=True)),
                ('plan_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_production_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FourMChangeInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('part_no', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=255)),
                ('lot_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('ok_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('rej_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('parameter_specs', models.CharField(blank=True, max_length=255, null=True)),
                ('before_1', models.CharField(blank=True, max_length=100, null=True)),
                ('before_2', models.CharField(blank=True, max_length=100, null=True)),
                ('before_3', models.CharField(blank=True, max_length=100, null=True)),
                ('before_4', models.CharField(blank=True, max_length=100, null=True)),
                ('before_5', models.CharField(blank=True, max_length=100, null=True)),
                ('after_1', models.CharField(blank=True, max_length=100, null=True)),
                ('after_2', models.CharField(blank=True, max_length=100, null=True)),
                ('after_3', models.CharField(blank=True, max_length=100, null=True)),
                ('after_4', models.CharField(blank=True, max_length=100, null=True)),
                ('after_5', models.CharField(blank=True, max_length=100, null=True)),
                ('inspected_by', models.CharField(max_length=150)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inspection_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'four_m_change_inspection',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FourMChangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_man', models.CharField(choices=[('OK', 'No Change'), ('CHANGE', 'Change Implemented'), ('NOT_SET', 'Not Set')], default='NOT_SET', max_length=10)),
                ('status_machine', models.CharField(choices=[('OK', 'No Change'), ('CHANGE', 'Change Implemented'), ('NOT_SET', 'Not Set')], default='NOT_SET', max_length=10)),
                ('status_material', models.CharField(choices=[('OK', 'No Change'), ('CHANGE', 'Change Implemented'), ('NOT_SET', 'Not Set')], default='NOT_SET', max_length=10)),
                ('status_method', models.CharField(choices=[('OK', 'No Change'), ('CHANGE', 'Change Implemented'), ('NOT_SET', 'Not Set')], default='NOT_SET', max_length=10)),
                ('time', models.TimeField()),
                ('machine_no', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('nature_of_change', models.CharField(max_length=100)),
                ('action_taken', models.CharField(max_length=255)),
                ('part_info', models.CharField(max_length=255)),
                ('operation_no', models.CharField(max_length=100)),
                ('setup_approval', models.CharField(max_length=50)),
                ('training_provided', models.CharField(max_length=50)),
                ('retro_qty_checked', models.IntegerField(blank=True, null=True)),
                ('retro_entry_qty', models.IntegerField(blank=True, null=True)),
                ('retro_qty_ok', models.CharField(max_length=20)),
                ('retro_rw', models.CharField(max_length=20)),
                ('retro_scrap', models.CharField(max_length=20)),
                ('cont_qty_checked', models.IntegerField(blank=True, null=True)),
                ('cont_entry_qty', models.IntegerField(blank=True, null=True)),
                ('cont_qty_ok', models.CharField(max_length=20)),
                ('cont_rw', models.CharField(max_length=20)),
                ('cont_scrap', models.CharField(max_length=20)),
                ('customer', models.CharField(max_length=255)),
                ('dispatch_date', models.DateField(default=datetime.date.today)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'four_m_change_records',
            },
        ),
    ]
