# Generated by Django 5.2.5 on 2026-04-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_dailyproductionplan_fourmchangeinspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductionplan',
            name='achieved_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dailyproductionplan',
            name='plant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
