# Generated by Django 5.2.5 on 2026-04-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_dailyproductionplan_achieved_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipchangedressing',
            name='dressing_status',
        ),
        migrations.RemoveField(
            model_name='tipchangedressing',
            name='tip_dressing',
        ),
        migrations.AddField(
            model_name='tipchangedressing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tipchangedressing',
            name='machine_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tipchangedressing',
            name='machine_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tipchangedressing',
            name='operation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tipchangedressing',
            name='plant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='tipchangedressing',
            table='tip_change_monitoring',
        ),
    ]
