# Generated by Django 5.2.5 on 2026-04-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_tipchangedressing_dressing_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_date', models.DateField(blank=True, null=True)),
                ('part_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_stock', models.IntegerField(blank=True, default=0, null=True)),
                ('schedule_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('planned_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorObservanceChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('part_operation', models.CharField(blank=True, max_length=255, null=True)),
                ('checkpoints', models.JSONField(blank=True, default=list)),
                ('prepared_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorObservancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_date', models.DateField(auto_now_add=True)),
                ('plan_year', models.CharField(blank=True, max_length=10, null=True)),
                ('plan_month', models.CharField(blank=True, max_length=20, null=True)),
                ('operators_data', models.JSONField(blank=True, default=list)),
                ('prepared_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PMChecklistMHE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_date', models.DateField(blank=True, null=True)),
                ('part_name', models.CharField(blank=True, max_length=255, null=True)),
                ('trolley_no', models.CharField(blank=True, max_length=255, null=True)),
                ('pm_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('checkpoints', models.JSONField(blank=True, default=list)),
                ('checked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('general_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
