# Generated by Django 5.2.5 on 2026-04-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_monthlyproductionplan_operatorobservancechecklist_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monthlyproductionplan',
            table='monthly_production_plan',
        ),
        migrations.AlterModelTable(
            name='operatorobservancechecklist',
            table='operator_observance_checklist',
        ),
        migrations.AlterModelTable(
            name='operatorobservanceplan',
            table='operator_observance_plan',
        ),
        migrations.AlterModelTable(
            name='pmchecklistmhe',
            table='pm_checklist_mhe',
        ),
    ]
