# Generated by Django 5.2.5 on 2026-04-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_monthlyproductionplan_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_date', models.DateField(blank=True, null=True)),
                ('revalidation_date', models.DateField(blank=True, null=True)),
                ('process_name', models.CharField(blank=True, max_length=200, null=True)),
                ('material_details', models.CharField(blank=True, max_length=200, null=True)),
                ('machine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('process_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('part_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fixture_no', models.CharField(blank=True, max_length=100, null=True)),
                ('operators', models.JSONField(default=list)),
                ('parameters', models.JSONField(default=list)),
                ('trials', models.JSONField(default=list)),
                ('final_params', models.JSONField(default=list)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'manufacturing_process_validation',
            },
        ),
        migrations.CreateModel(
            name='ProjectionWelderQual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wps_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('welding_process', models.CharField(default='PROJECTION WELDING', max_length=100)),
                ('base_metal', models.CharField(blank=True, max_length=100, null=True)),
                ('base_metal_thickness', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('trials', models.JSONField(default=list)),
                ('welder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('conducted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projection_welder_qualification',
            },
        ),
        migrations.CreateModel(
            name='SpotWelderQual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wps_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('welding_process', models.CharField(default='Spot Welding', max_length=100)),
                ('base_metal', models.CharField(blank=True, max_length=100, null=True)),
                ('base_metal_thickness', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('gun_type', models.CharField(blank=True, max_length=100, null=True)),
                ('trials', models.JSONField(default=list)),
                ('welder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('conducted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'spot_welder_qualification',
            },
        ),
        migrations.CreateModel(
            name='TigMigWelderQual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wps_no', models.CharField(blank=True, max_length=100, null=True)),
                ('testing_date', models.DateField(blank=True, null=True)),
                ('welding_process', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('base_metal', models.CharField(blank=True, max_length=100, null=True)),
                ('base_metal_thickness', models.CharField(blank=True, max_length=100, null=True)),
                ('base_metal_size', models.CharField(blank=True, max_length=100, null=True)),
                ('welding_position', models.CharField(blank=True, max_length=100, null=True)),
                ('filler_material', models.CharField(blank=True, max_length=100, null=True)),
                ('filler_material_size', models.CharField(blank=True, max_length=100, null=True)),
                ('shielding_gas', models.CharField(blank=True, max_length=100, null=True)),
                ('wire_feed_speed', models.CharField(blank=True, max_length=100, null=True)),
                ('trials', models.JSONField(default=list)),
                ('test_results', models.JSONField(default=dict)),
                ('welder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('conducted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tig_mig_welder_qualification',
            },
        ),
    ]
