# Generated by Django 5.2.5 on 2026-04-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_processvalidation_projectionwelderqual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoherenceChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(blank=True, max_length=200, null=True)),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('operations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_coherence_checklist',
            },
        ),
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('part_details', models.CharField(blank=True, max_length=200, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('problem_description', models.TextField(blank=True, null=True)),
                ('counter_measure', models.TextField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('horizontal_action', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='OPEN', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_customer_complaint',
            },
        ),
        migrations.CreateModel(
            name='LayoutInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(blank=True, max_length=200, null=True)),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('sample_size', models.CharField(blank=True, max_length=50, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('inspections', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_layout_inspection',
            },
        ),
        migrations.CreateModel(
            name='ProcessAuditChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name_no', models.CharField(blank=True, max_length=200, null=True)),
                ('machine_model', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('auditor', models.CharField(blank=True, max_length=100, null=True)),
                ('auditee', models.CharField(blank=True, max_length=100, null=True)),
                ('observations', models.JSONField(default=list)),
                ('remarks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_process_audit_checksheet',
            },
        ),
        migrations.CreateModel(
            name='ProductAuditPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('rev_no', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('plan_year', models.CharField(blank=True, max_length=50, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('audit_rows', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'monthly_product_audit_plan',
            },
        ),
    ]
