# Generated by Django 5.2.5 on 2026-04-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_coherencechecklist_customercomplaint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processauditchecksheet',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='processauditchecksheet',
            name='remarks',
        ),
        migrations.AddField(
            model_name='processauditchecksheet',
            name='audit_details',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterModelTable(
            name='processauditchecksheet',
            table='process_audit_checksheet',
        ),
    ]
