# Generated by Django 5.2.5 on 2026-04-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_processauditchecksheet_observations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('month_year', models.CharField(blank=True, max_length=50, null=True)),
                ('performance_indicators', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_customer_satisfaction',
            },
        ),
        migrations.CreateModel(
            name='MinutesOfMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('aot_members', models.TextField(blank=True, null=True)),
                ('supplier_members', models.TextField(blank=True, null=True)),
                ('discussions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_minutes_of_meeting',
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('part_details', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_qty', models.CharField(blank=True, max_length=50, null=True)),
                ('warranty_defect', models.TextField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=50, null=True)),
                ('rejection_root_cause', models.TextField(blank=True, null=True)),
                ('disposal_action', models.CharField(blank=True, max_length=255, null=True)),
                ('capa_analysis', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_warranty_claim',
            },
        ),
    ]
