# Generated by Django 5.2.5 on 2026-04-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_customersatisfaction_minutesofmeeting_warrantyclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductionplan',
            name='machine_bd_time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dailyproductionplan',
            name='production_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproductionplan',
            name='production_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproductionplan',
            name='rm_coil_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dailyproductionplan',
            name='tool_bd_time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dailyproductionplan',
            name='tool_setup_time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dailyproductionplan',
            name='total_working_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
