# Generated by Django 5.2.5 on 2026-04-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_dailyproductionplan_machine_bd_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('machine_type_no', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_machine_breakdownsummary',
            },
        ),
        migrations.CreateModel(
            name='MachineCriticalSpare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('spare_description', models.CharField(blank=True, max_length=255, null=True)),
                ('model_description', models.CharField(blank=True, max_length=255, null=True)),
                ('box_location', models.CharField(blank=True, max_length=255, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=150, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('spare_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_machine_critical_spare',
            },
        ),
        migrations.CreateModel(
            name='ToolBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('tool_name', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_tool_breakdownsummary',
            },
        ),
        migrations.CreateModel(
            name='ToolCriticalSpare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('spare_description', models.CharField(blank=True, max_length=255, null=True)),
                ('model_description', models.CharField(blank=True, max_length=255, null=True)),
                ('box_location', models.CharField(blank=True, max_length=255, null=True)),
                ('spare_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qa_tool_critical_spare',
            },
        ),
    ]
