# Generated by Django 5.2.5 on 2026-04-28 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_machinebreakdown_machinecriticalspare_toolbreakdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTrackHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('report_name', models.CharField(max_length=150)),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
