# Generated by Django 5.2.5 on 2026-04-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_reporttrackhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductionplan',
            name='shift',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
