# Generated by Django 5.2.5 on 2026-05-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_dailyproductionplan_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_no', models.IntegerField(help_text='1 for Plant 1, 2 for Plant 2')),
                ('machine_no', models.CharField(max_length=10)),
                ('event_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('shift', models.CharField(max_length=5)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Machine_Event_Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['plant_no', 'machine_no', 'timestamp'], name='Machine_Eve_plant_n_500fd9_idx')],
            },
        ),
    ]
