# Generated by Django 5.2.5 on 2026-05-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_machineeventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyDowntimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('machine_no', models.CharField(max_length=10)),
                ('idle_time', models.IntegerField(default=0)),
                ('shift', models.CharField(max_length=5)),
                ('status_type', models.CharField(default='Idle', max_length=20)),
                ('reason_category', models.CharField(default='Uncategorized', max_length=100)),
                ('specific_reason', models.CharField(default='Supervisor not save the information', max_length=255)),
            ],
            options={
                'db_table': 'hourly_downtime_logs',
                'ordering': ['-timestamp', 'machine_no'],
                'indexes': [models.Index(fields=['timestamp', 'machine_no'], name='hourly_down_timesta_36eb8f_idx'), models.Index(fields=['machine_no', 'timestamp'], name='hourly_down_machine_0ce9fc_idx')],
            },
        ),
    ]
