# Generated by Django 5.2.5 on 2026-05-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_hourlydowntimelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlydowntimelog',
            name='status_type',
        ),
        migrations.AddField(
            model_name='hourlydowntimelog',
            name='machine_status',
            field=models.CharField(choices=[('ONLINE', 'Machine is Online (But Idle)'), ('OFFLINE', 'Machine is Offline (No Signal)')], default='ONLINE', max_length=20),
        ),
    ]
