# Generated by Django 5.2.5 on 2026-06-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_redbinanalysisreport_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redbinanalysisreport',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
