# Generated by Django 5.2.5 on 2026-06-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_created_at_redbinanalysisreport_created_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolBreakdownIntimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(blank=True, default='AOT-F-BD-01', max_length=50, null=True)),
                ('reporter_name', models.CharField(max_length=255)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('machine_name_no', models.CharField(max_length=255)),
                ('report_time', models.TimeField(blank=True, null=True)),
                ('breakdown_details', models.TextField()),
                ('prod_supervisor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('maint_date', models.DateField(blank=True, null=True)),
                ('maint_time', models.TimeField(blank=True, null=True)),
                ('time_taken_to_rectify', models.CharField(blank=True, max_length=100, null=True)),
                ('men_engaged', models.IntegerField(blank=True, null=True)),
                ('action_taken_details', models.TextField(blank=True, null=True)),
                ('maint_incharge_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='OK', max_length=10)),
                ('qa_date', models.DateField(blank=True, null=True)),
                ('qa_time', models.TimeField(blank=True, null=True)),
                ('nc_verification', models.CharField(blank=True, max_length=255, null=True)),
                ('qa_incharge_name', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(default='hindi', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tool_breakdown_slip',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
