# Generated by Django 5.2.5 on 2026-06-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_toolbreakdownintimation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressorMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, default='Compressor', max_length=100, null=True)),
                ('date', models.DateField()),
                ('machine_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_personnel', models.CharField(blank=True, max_length=100, null=True)),
                ('checkpoints', models.JSONField(default=list, help_text='Stores the checklist array')),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compressor_maintenance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LatheMachineMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, default='LATHE MACHINE', max_length=100, null=True)),
                ('date', models.DateField()),
                ('machine_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_personnel', models.CharField(blank=True, max_length=100, null=True)),
                ('checkpoints', models.JSONField(default=list, help_text='Stores the checklist array')),
                ('prepared_by', models.CharField(max_length=100)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lathe_machine_maintenance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpotWeldingMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, default='SPOT WELDING M/C', max_length=100, null=True)),
                ('date', models.DateField()),
                ('machine_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_personnel', models.CharField(blank=True, max_length=100, null=True)),
                ('checkpoints', models.JSONField(default=list, help_text='Stores the checklist array')),
                ('prepared_by', models.CharField(max_length=100)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'spot_welding_maintenance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurfaceGrinderMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, default='SURFACE GRINDER', max_length=100, null=True)),
                ('date', models.DateField()),
                ('machine_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_personnel', models.CharField(blank=True, max_length=100, null=True)),
                ('checkpoints', models.JSONField(default=list, help_text='Stores the checklist array')),
                ('prepared_by', models.CharField(max_length=100)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'surface_grinder_maintenance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TigWeldingMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('machine_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_personnel', models.CharField(blank=True, max_length=100, null=True)),
                ('checkpoints', models.JSONField(default=list, help_text='Stores the checklist array')),
                ('prepared_by', models.CharField(max_length=100)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tig_welding_maintenance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VerticalDrillMachineMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, default='VERTICAL DRILL MACHINE', max_length=100, null=True)),
                ('date', models.DateField()),
                ('machine_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_personnel', models.CharField(blank=True, max_length=100, null=True)),
                ('checkpoints', models.JSONField(default=list, help_text='Stores the checklist array')),
                ('prepared_by', models.CharField(max_length=100)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vertical_drill_machine_maintenance',
                'managed': True,
            },
        ),
    ]
