# Generated by Django 5.2.5 on 2026-06-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_compressormaintenance_lathemachinemaintenance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseGrinderMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, default='Base Grinder', max_length=100, null=True)),
                ('date', models.DateField()),
                ('machine_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_personnel', models.CharField(blank=True, max_length=100, null=True)),
                ('checkpoints', models.JSONField(default=list, help_text='Stores the checklist array')),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'base_grinder_maintenance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BeltGrinderMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, default='BELT GRINDER', max_length=100, null=True)),
                ('date', models.DateField()),
                ('machine_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_personnel', models.CharField(blank=True, max_length=100, null=True)),
                ('checkpoints', models.JSONField(default=list, help_text='Stores the checklist array')),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'belt_grinder_maintenance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DipMoldingMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, default='Dip Molding Machine', max_length=100, null=True)),
                ('date', models.DateField()),
                ('machine_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_personnel', models.CharField(blank=True, max_length=100, null=True)),
                ('checkpoints', models.JSONField(default=list, help_text='Stores the checklist array')),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dip_molding_maintenance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PartMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('part_name', models.CharField(max_length=255)),
                ('part_no', models.CharField(blank=True, max_length=255, null=True)),
                ('part_model', models.CharField(blank=True, max_length=255, null=True)),
                ('inspection_data', models.JSONField()),
            ],
            options={
                'db_table': 'master_data_incoming_material_inspection',
            },
        ),
        migrations.CreateModel(
            name='PipeCuttingMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, default='Pipe Cutter', max_length=100, null=True)),
                ('date', models.DateField()),
                ('machine_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_personnel', models.CharField(blank=True, max_length=100, null=True)),
                ('checkpoints', models.JSONField(default=list, help_text='Stores the checklist array')),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pipe_cutting_maintenance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServoPressMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, default='Servo Press', max_length=100, null=True)),
                ('date', models.DateField()),
                ('machine_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_personnel', models.CharField(blank=True, max_length=100, null=True)),
                ('checkpoints', models.JSONField(default=list, help_text='Stores the checklist array')),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'servo_press_maintenance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VibraMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(blank=True, default='Vibra', max_length=100, null=True)),
                ('date', models.DateField()),
                ('machine_no', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_personnel', models.CharField(blank=True, max_length=100, null=True)),
                ('checkpoints', models.JSONField(default=list, help_text='Stores the checklist array')),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vibra_maintenance',
                'managed': True,
            },
        ),
    ]
