# Generated by Django 5.2.5 on 2026-06-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_basegrindermaintenance_beltgrindermaintenance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNCMaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=150)),
                ('machine_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
                ('maintenance_personnel', models.CharField(max_length=150)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cnc_maintenance_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HydraulicPMCheckSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(default='HYDRAULIC MACHINE', max_length=150)),
                ('machine_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
                ('maintenance_personnel', models.CharField(max_length=150)),
                ('checkpoints', models.JSONField(blank=True, default=list)),
                ('prepared_by', models.CharField(max_length=150)),
                ('checked_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hydraulic_pm_checksheet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachinePreventiveMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=150)),
                ('machine_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
                ('maintenance_personnel', models.CharField(max_length=150)),
                ('checkpoints', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'machine_preventive_maintenance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PowerPressPMCheckSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(default='POWER PRESS', max_length=150)),
                ('machine_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
                ('checkpoints', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'power_press_pm_checksheet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectionWeldingPMCheckSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(default='PROJECTION WELDING', max_length=150)),
                ('machine_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
                ('maintenance_personnel', models.CharField(max_length=150)),
                ('checkpoints', models.JSONField(blank=True, default=list)),
                ('prepared_by', models.CharField(max_length=150)),
                ('checked_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projection_welding_pm_checksheet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerticalMillingMachineCheckSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(default='VERTICAL MILLING MACHINE', max_length=150)),
                ('machine_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('specification', models.CharField(blank=True, max_length=255, null=True)),
                ('maintenance_personnel', models.CharField(max_length=150)),
                ('checkpoints', models.JSONField(blank=True, default=list)),
                ('prepared_by', models.CharField(max_length=150)),
                ('checked_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vertical_milling_machine_checksheet',
                'ordering': ['-created_at'],
            },
        ),
    ]
