# Generated by Django 5.2.5 on 2026-06-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_cncmaintenancereport_hydraulicpmchecksheet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourMDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(blank=True, null=True)),
                ('machine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('man', models.CharField(blank=True, max_length=255, null=True)),
                ('machine', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('date_filled', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'four_m_display_board',
            },
        ),
    ]
