# Generated by Django 5.2.5 on 2026-06-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_fourmdisplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourMSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('part_name_no', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_change', models.CharField(blank=True, max_length=255, null=True)),
                ('change_detail', models.TextField(blank=True, null=True)),
                ('retro_total_qty', models.IntegerField(blank=True, null=True)),
                ('retro_ok_qty', models.IntegerField(blank=True, null=True)),
                ('retro_rej_qty', models.IntegerField(blank=True, null=True)),
                ('status_after_final', models.CharField(blank=True, max_length=255, null=True)),
                ('action_for_ng', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('sup_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('sign_prod_head', models.CharField(blank=True, max_length=255, null=True)),
                ('sign_qa_head', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'four_m_summary_sheet',
            },
        ),
    ]
