# Generated by Django 5.2.5 on 2026-06-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_fourmsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(help_text='Assembly / Part Name', max_length=255)),
                ('part_no', models.CharField(blank=True, help_text='Part Number', max_length=100, null=True)),
                ('done_on_date', models.DateField()),
                ('fixture_no', models.CharField(max_length=100)),
                ('operation_name', models.CharField(max_length=255)),
                ('checklist_data', models.JSONField(default=list, help_text='Stores the 8 checklist points data')),
                ('pin_chart_data', models.JSONField(default=list, help_text='Stores 12 rows of Pin data')),
                ('bush_chart_data', models.JSONField(default=list, help_text='Stores 12 rows of Bush data')),
                ('inspected_by', models.CharField(help_text='Engineer Sign / Name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fixture Maintenance Record',
                'verbose_name_plural': 'Fixture Maintenance Records',
                'db_table': 'fixture_maintenance_records',
            },
        ),
    ]
