# Generated by Django 5.2.5 on 2026-06-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_fixturemaintenancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMaterialInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(default='ATOMONE TECHNOLOGIES PVT.LTD', max_length=255)),
                ('customer', models.CharField(max_length=255)),
                ('part_name', models.CharField(max_length=255)),
                ('part_no', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('mtc', models.CharField(blank=True, max_length=10, null=True)),
                ('ga_nga', models.CharField(blank=True, max_length=10, null=True)),
                ('coil_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.CharField(blank=True, max_length=50, null=True)),
                ('inspection_data', models.JSONField(default=list, help_text='Stores array of objects containing parameter, specification, inspMethod, observations array, and remark')),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incoming_material_inspection_report',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
