# Generated by Django 5.2.5 on 2026-06-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_incomingmaterialinspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmaterialinspection',
            name='part_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
