# Generated by Django 5.2.5 on 2026-06-11 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_incomingmaterialinspection_part_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('department_name', models.CharField(max_length=100)),
                ('report_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Report Log',
                'verbose_name_plural': 'User Report Logs',
                'db_table': 'user_report_activity_logs',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(choices=[('Plant 1', 'Plant 1'), ('Plant 2', 'Plant 2'), ('QA Hub', 'QA Hub'), ('Production Hub', 'Production Hub'), ('Maintenance Hub', 'Maintenance Hub')], default='Plant 1', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_department_profiles',
            },
        ),
    ]
