# Generated by Django 5.2.5 on 2026-06-11 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_reportactivitylog_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportactivitylog',
            options={},
        ),
        migrations.AddField(
            model_name='reportactivitylog',
            name='status',
            field=models.CharField(default='In Progress', max_length=255),
        ),
        migrations.CreateModel(
            name='QANotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportactivitylog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qa_hub_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
