# Generated by Django 5.2.5 on 2026-06-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_reportactivitylog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportactivitylog',
            name='record_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
