# Generated by Django 5.2.5 on 2026-06-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_reportactivitylog_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Alternate/Direct Email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('QA', 'Quality Assurance (QA)'), ('Production', 'Production'), ('Maintenance', 'Maintenance'), ('Management', 'Management')], default='QA', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique Employee Code', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(choices=[('Plant 1', 'Plant 1'), ('Plant 2', 'Plant 2'), ('HQ', 'Headquarters')], default='Plant 1', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
