# Generated by Django 6.0.6 on 2026-06-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_userprofile_department_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant2hourlyidletime',
            options={'managed': False, 'ordering': ['-timestamp', 'machine_no']},
        ),
        migrations.AlterField(
            model_name='fourmchangerecord',
            name='cont_qty_ok',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fourmchangerecord',
            name='cont_rw',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fourmchangerecord',
            name='cont_scrap',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fourmchangerecord',
            name='retro_qty_ok',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fourmchangerecord',
            name='retro_rw',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fourmchangerecord',
            name='retro_scrap',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
