# Generated by Django 5.2.5 on 2026-06-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_plant2hourlyidletime_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourmchangerecord',
            name='cont_entry_qty',
        ),
        migrations.RemoveField(
            model_name='fourmchangerecord',
            name='retro_entry_qty',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, help_text='Designation of the User', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full Name of the User', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_department_profiles',
        ),
    ]
                              