# Generated by Django 6.0.6 on 2026-06-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_plant2hourlyidletime_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourMInformationSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('machine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('man', models.CharField(blank=True, max_length=50, null=True)),
                ('machine', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('change_description', models.TextField(blank=True, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date_filled', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'four_m_information_sheet',
            },
        ),
    ]
