# Generated by Django 5.2.5 on 2026-06-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_fourmchangerecord_cont_entry_qty_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_department_profiles',
        ),
    ]
