# Generated by Django 5.2.5 on 2026-06-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_fourminformationsheet'),
        ('api', '0048_alter_userprofile_table'),
    ]

    operations = [
    ]
