# Generated by Django 5.2.5 on 2026-06-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_merge_20260623_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportactivitylog',
            name='form_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportactivitylog',
            name='hub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fourminformationsheet',
            name='date_filled',
            field=models.DateField(),
        ),
    ]
