# Generated by Django 6.0.6 on 2026-06-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_reportactivitylog_form_key_reportactivitylog_hub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourmchangerecord',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fourminformationsheet',
            name='date_filled',
            field=models.DateField(auto_now_add=True),
        ),
    ]
