# Generated by Django 5.2.5 on 2026-06-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_reportactivitylog_form_key_reportactivitylog_hub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportactivitylog',
            name='form_key',
        ),
        migrations.RemoveField(
            model_name='reportactivitylog',
            name='hub',
        ),
        migrations.AlterField(
            model_name='fourminformationsheet',
            name='date_filled',
            field=models.DateField(auto_now_add=True),
        ),
    ]
