# Generated by Django 6.0.6 on 2026-06-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_fourmchangerecord_dispatch_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourmchangerecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
