# Generated by Django 5.2.5 on 2026-06-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_reportactivitylog_form_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportactivitylog',
            name='approved_or_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportactivitylog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
