# Generated by Django 6.0.6 on 2026-06-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_fourmchangerecord_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionreport',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
    ]
