# Generated by Django 5.2.5 on 2026-06-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_reportactivitylog_approved_or_rejected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportactivitylog',
            name='approved_or_rejected_at',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
