# Generated by Django 6.0.6 on 2026-06-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_inspectionreport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
