# Generated by Django 5.2.5 on 2026-06-29 09:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_reportactivitylog_approved_or_rejected_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportactivitylog',
            name='timestamp',
            field=models.CharField(default=api.models.current_datetime_string, max_length=19),
        ),
    ]
