# Generated by Django 5.2.5 on 2026-07-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_reportactivitylog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinehistorycard',
            name='plant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
