# Generated by Django 5.2.5 on 2026-07-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_reportactivitylog_timestamp'),
    ]

    operations = [
    migrations.SeparateDatabaseAndState(
        database_operations=[
            migrations.RunSQL(
                sql="""
                CREATE SCHEMA IF NOT EXISTS maintenance;

                DO $$
                BEGIN
                    IF to_regclass('maintenance.machine_history_card') IS NULL
                       AND to_regclass('public.machine_history_card') IS NOT NULL THEN
                        ALTER TABLE public.machine_history_card SET SCHEMA maintenance;
                    END IF;
                END $$;

                ALTER TABLE IF EXISTS maintenance.machine_history_card
                ADD COLUMN IF NOT EXISTS plant varchar(50) NULL;
                """,
                reverse_sql="""
                ALTER TABLE IF EXISTS maintenance.machine_history_card
                DROP COLUMN IF EXISTS plant;
                """,
            )
        ],
        state_operations=[
            migrations.AddField(
                model_name="machinehistorycard",
                name="plant",
                field=models.CharField(max_length=50, blank=True, null=True),
            ),
            migrations.AlterModelTable(
                name="machinehistorycard",
                table='"maintenance"."machine_history_card"',
            ),
        ],
    ),
]
