# Generated by Django 5.2.5 on 2026-07-02 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_machinehistorycard_plant'),
    ]

    operations = [
    migrations.SeparateDatabaseAndState(
        database_operations=[
            migrations.RunSQL(
                sql="""
                    CREATE SCHEMA IF NOT EXISTS machine_maintenance;

                    DO $$
                    BEGIN
                        IF to_regclass('machine_maintenance.machine_breakdown_intimation') IS NOT NULL THEN
                            -- Table is already in correct schema, do nothing
                            NULL;
                        ELSIF to_regclass('public.machine_breakdown_intimation') IS NOT NULL THEN
                            ALTER TABLE public.machine_breakdown_intimation
                            SET SCHEMA machine_maintenance;
                        END IF;
                    END $$;
                """,
                reverse_sql="""
                    DO $$
                    BEGIN
                        IF to_regclass('public.machine_breakdown_intimation') IS NOT NULL THEN
                            NULL;
                        ELSIF to_regclass('machine_maintenance.machine_breakdown_intimation') IS NOT NULL THEN
                            ALTER TABLE machine_maintenance.machine_breakdown_intimation
                            SET SCHEMA public;
                        END IF;
                    END $$;
                """,
            ),
        ],
        state_operations=[
            migrations.AlterModelTable(
                name="machinebreakdownintimation",
                table='"machine_maintenance"."machine_breakdown_intimation"',
            ),
        ],
    ),
]
