# Generated by Django 5.2.5 on 2026-07-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_machinebreakdownintimation_table'),
    ]

    operations = [
    migrations.SeparateDatabaseAndState(
        database_operations=[
            migrations.RunSQL(
                sql="""
                    CREATE SCHEMA IF NOT EXISTS machine_maintenance;

                    DO $$
                    BEGIN
                        IF to_regclass('machine_maintenance.machine_checksheet_report') IS NOT NULL THEN
                            NULL;
                        ELSIF to_regclass('public.machine_checksheet_report') IS NOT NULL THEN
                            ALTER TABLE public.machine_checksheet_report
                            SET SCHEMA machine_maintenance;
                        END IF;

                        IF to_regclass('machine_maintenance.machine_checksheet_observation') IS NOT NULL THEN
                            NULL;
                        ELSIF to_regclass('public.machine_checksheet_observation') IS NOT NULL THEN
                            ALTER TABLE public.machine_checksheet_observation
                            SET SCHEMA machine_maintenance;
                        END IF;
                    END $$;
                """,
                reverse_sql="""
                    DO $$
                    BEGIN
                        IF to_regclass('public.machine_checksheet_observation') IS NOT NULL THEN
                            NULL;
                        ELSIF to_regclass('machine_maintenance.machine_checksheet_observation') IS NOT NULL THEN
                            ALTER TABLE machine_maintenance.machine_checksheet_observation
                            SET SCHEMA public;
                        END IF;

                        IF to_regclass('public.machine_checksheet_report') IS NOT NULL THEN
                            NULL;
                        ELSIF to_regclass('machine_maintenance.machine_checksheet_report') IS NOT NULL THEN
                            ALTER TABLE machine_maintenance.machine_checksheet_report
                            SET SCHEMA public;
                        END IF;
                    END $$;
                """,
            ),
        ],
        state_operations=[
            migrations.AlterModelTable(
                name="machinechecksheetreport",
                table='"machine_maintenance"."machine_checksheet_report"',
            ),
            migrations.AlterModelTable(
                name="machinechecksheetobservation",
                table='"machine_maintenance"."machine_checksheet_observation"',
            ),
        ],
    ),
]
