# Generated by Django 5.2.5 on 2026-07-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_alter_machinechecksheetobservation_table_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE SCHEMA IF NOT EXISTS machine_maintenance;

                        DO $$
                        BEGIN
                            IF to_regclass('machine_maintenance.machine_preventive_maintenance') IS NOT NULL THEN
                                -- Table is already in correct schema, do nothing
                                NULL;
                            ELSIF to_regclass('public.machine_preventive_maintenance') IS NOT NULL THEN
                                ALTER TABLE public.machine_preventive_maintenance
                                SET SCHEMA machine_maintenance;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="""
                        DO $$
                        BEGIN
                            IF to_regclass('public.machine_preventive_maintenance') IS NOT NULL THEN
                                NULL;
                            ELSIF to_regclass('machine_maintenance.machine_preventive_maintenance') IS NOT NULL THEN
                                ALTER TABLE machine_maintenance.machine_preventive_maintenance
                                SET SCHEMA public;
                            END IF;
                        END $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name="machinepreventivemaintenance",
                    table='"machine_maintenance"."machine_preventive_maintenance"',
                ),
            ],
        ),
    ]
