# Generated by Django 5.2.5 on 2026-07-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_machinepreventivemaintenance_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdealTimeSegmentReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_location', models.CharField(db_index=True, max_length=50)),
                ('machine_no', models.IntegerField(db_index=True)),
                ('ideal_mode', models.CharField(choices=[('ONLINE', 'Online Ideal'), ('OFFLINE', 'Offline Ideal')], db_index=True, max_length=20)),
                ('ideal_start_at', models.DateTimeField(db_index=True)),
                ('ideal_end_at', models.DateTimeField(db_index=True)),
                ('ideal_time', models.PositiveIntegerField(default=0)),
                ('closed_by', models.CharField(blank=True, choices=[('COUNT_RESUME', 'Count Resume'), ('MACHINE_ON', 'Machine On'), ('MACHINE_OFF', 'Machine Off'), ('HOUR_CHANGE', 'Hour Change'), ('SHIFT_END', 'Shift End')], max_length=30, null=True)),
                ('reason', models.CharField(blank=True, default='Uncategorized', max_length=100, null=True)),
                ('specific_reason', models.CharField(blank=True, default='Reason Not Provided', max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('shift', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'db_table': '"live_data"."ideal_time_segments_reason"',
                'ordering': ['-ideal_start_at'],
                'indexes': [models.Index(fields=['plant_location', 'machine_no', 'shift'], name='ideal_time__plant_l_82575e_idx'), models.Index(fields=['plant_location', 'ideal_mode'], name='ideal_time__plant_l_cc8bcc_idx'), models.Index(fields=['ideal_start_at', 'ideal_end_at'], name='ideal_time__ideal_s_3ada6d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ideal_end_at__gt', models.F('ideal_start_at'))), name='ideal_end_after_start'), models.UniqueConstraint(fields=('plant_location', 'machine_no', 'ideal_mode', 'ideal_start_at', 'ideal_end_at'), name='unique_ideal_time_segment')],
            },
        ),
    ]
