# Generated by Django 5.2.5 on 2026-07-28 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_idealtimesegmentreason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'managed': True, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='operatorassignment',
            options={'managed': True},
        ),
    ]
