# Generated by Django 5.2.5 on 2026-08-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_remove_operatorassignment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idealtimesegmentreason',
            name='report_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='idealtimesegmentreason',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idealtimesegmentreason',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
