# Generated by Django 5.2.5 on 2026-08-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_idealtimesegmentreason_report_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idealtimesegmentreason',
            name='report_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('LEGACY', 'Legacy')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
