# Generated by Django 5.2.5 on 2026-08-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_idealtimesegmentreason_report_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='idealtimesegmentreason',
            index=models.Index(fields=['plant_location', 'machine_no', 'report_status', 'ideal_start_at'], name='ideal_pending_lookup_idx'),
        ),
    ]
