# Generated by Django 5.2.5 on 2026-08-24 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_idealtimesegmentreason_ideal_pending_lookup_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='ideal_mode',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Online Idle'), ('OFFLINE', 'Offline')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='idle_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GENERAL', 'General Notification'), ('IDLE_REASON', 'Idle Reason Required')], db_index=True, default='GENERAL', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='plant_location',
            field=models.CharField(blank=True, choices=[('Plant 1', 'Plant 1'), ('Plant 2', 'Plant 2')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='reason_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='specific_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['plant_location', 'status', 'created_at'], name='notif_plant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'event_key'), name='unique_idle_notification_per_user_event'),
        ),
    ]
