# Generated by Django 5.2.5 on 2026-08-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_notification_event_key_notification_ideal_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='idle_ended_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
