# Generated by Django 5.2.5 on 2026-08-25 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_notification_idle_ended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='idealtimesegmentreason',
            name='ideal_end_after_start',
        ),
        migrations.RemoveIndex(
            model_name='idealtimesegmentreason',
            name='ideal_time__plant_l_82575e_idx',
        ),
        migrations.RemoveIndex(
            model_name='idealtimesegmentreason',
            name='ideal_time__plant_l_cc8bcc_idx',
        ),
        migrations.RemoveIndex(
            model_name='idealtimesegmentreason',
            name='ideal_time__ideal_s_3ada6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='idealtimesegmentreason',
            name='ideal_pending_lookup_idx',
        ),
        migrations.AddField(
            model_name='idealtimesegmentreason',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='ideal_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.idealtimesegmentreason'),
        ),
        migrations.AlterField(
            model_name='idealtimesegmentreason',
            name='ideal_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idealtimesegmentreason',
            name='ideal_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='idealtimesegmentreason',
            index=models.Index(fields=['plant_location', 'machine_no', 'ideal_start_at'], name='ideal_machine_time_idx'),
        ),
        migrations.AddIndex(
            model_name='idealtimesegmentreason',
            index=models.Index(fields=['plant_location', 'report_status', 'machine_no', 'ideal_start_at'], name='ideal_pending_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='idealtimesegmentreason',
            index=models.Index(fields=['plant_location', 'ideal_mode', 'ideal_start_at'], name='ideal_mode_time_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notif_user_read_idx'),
        ),
        migrations.AddConstraint(
            model_name='idealtimesegmentreason',
            constraint=models.CheckConstraint(condition=models.Q(('ideal_end_at__isnull', True), ('ideal_end_at__gt', models.F('ideal_start_at')), _connector='OR'), name='ideal_end_after_start_or_open'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('ideal_event__isnull', False)), fields=('user', 'ideal_event'), name='unique_notification_user_ideal_event'),
        ),
    ]
