# Generated by Django 5.2.5 on 2026-08-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_notification_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idealtimesegmentreason',
            name='event_key',
        ),
    ]
