# Generated by Django 5.2.5 on 2026-09-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_remove_idealtimesegmentreason_event_key'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='idealtimesegmentreason',
            constraint=models.UniqueConstraint(condition=models.Q(('ideal_end_at__isnull', True)), fields=('plant_location', 'machine_no'), name='one_open_ideal_per_machine'),
        ),
    ]
